function(n19_has_compiler_flag flag result_var)
  include(CheckCXXCompilerFlag)
  check_cxx_compiler_flag(${flag} _flag_supported)
  set(${result_var} ${_flag_supported} PARENT_SCOPE)
endfunction()

function(print_box message)
  string(REPEAT "#" 60 border)
  message("\n${border}")
  message("# ${message}")
  message("${border}\n")
endfunction()
